# Generated by Django 3.0.1 on 2020-04-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='exp_month',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingprofile',
            name='exp_year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
